version: 2

references:
  test-steps: &test-steps
    - checkout
    - restore_cache:
        keys:
          - v2-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ checksum "package.json" }}
    - run:
        name: Enable Safari develop menu
        command: if [ $OS == "macos" ]; then sudo defaults write com.apple.Safari IncludeDevelopMenu -enable; else echo "skipping"; fi
    - run:
        name: Allow Safari automation
        command: if [ $OS == "macos" ]; then sudo /usr/bin/safaridriver --enable; else echo "skipping"; fi
    - run:
        name: Install dependencies
        command: npm install
    - run:
        name: Build
        command: npm run build
    - run:
        name: Build tests
        command: npm run ${BUILDTARGET}
    - run:
        name: Run tests
        command: npm run ${TESTTARGET}
    - save_cache:
        key: v2-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ arch }}-{{ checksum "package.json" }}
        paths:
          - node_modules

jobs:
  unittest-node8:
    docker:
      - image: circleci/node:8-browsers
    steps: *test-steps
    environment:
      BUILDTARGET: build:unittests
      TESTTARGET: test:unit
      OS: linux
  unittest-node10:
    docker:
      - image: circleci/node:10-browsers
    steps: *test-steps
    environment:
      BUILDTARGET: build:unittests
      TESTTARGET: test:unit
      OS: linux
  uitest-firefox:
    docker:
      - image: circleci/node:10-browsers
    steps: *test-steps
    environment:
      BUILDTARGET: build:uitests
      TESTTARGET: test:ui firefox
      OS: linux
  uitest-chrome:
    docker:
      - image: circleci/node:10-browsers
    steps: *test-steps
    environment:
      BUILDTARGET: build:uitests
      TESTTARGET: test:ui chrome
      OS: linux
  uitest-safari:
    macos:
      xcode: "10.1.0"
    steps: *test-steps
    environment:
      BUILDTARGET: build:uitests
      TESTTARGET: test:ui safari
      OS: macos
  lint:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-test-node8-{{ arch }}-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run lint

workflows:
  version: 2
  build:
    jobs:
      - unittest-node8
      - unittest-node10
      - uitest-firefox
      - uitest-chrome
      - uitest-safari
      - lint
